/**
 * Generate packages/service-store/src/full-services.ts from the full-artefact
 * service definitions on disk in data/services/.
 *
 * Every directory under data/services/ that carries the four core artefacts
 * (manifest.json, policy.json, state-model.json, consent.json) is embedded so
 * it seeds as a "full" service — on Cloudflare Workers there is no filesystem,
 * so the artefacts must be inlined here.
 *
 * Run with: npm run generate:full-services   (then npm run seed:services)
 *
 * Synthetic entries already in full-services.ts that have no matching directory
 * (e.g. agent-chat, triage) are preserved verbatim.
 */

import fs from "fs";
import path from "path";
import { ServiceGraphEngine } from "../packages/service-graph/src";
import {
  FULL_SERVICES as EXISTING,
  type FullServiceData,
} from "../packages/service-store/src/full-services";

const ROOT = path.join(__dirname, "..");
const SVC_DIR = path.join(ROOT, "data", "services");
const OUT = path.join(
  ROOT,
  "packages",
  "service-store",
  "src",
  "full-services.ts",
);

const CORE_ARTEFACTS = [
  "manifest.json",
  "policy.json",
  "state-model.json",
  "consent.json",
] as const;

/**
 * Legacy descriptive dirs whose artefacts are demo-tuned and currently served.
 * Each maps to the graph node id it replaces so today's service identity is
 * preserved exactly. `null` means it is served under its own manifest id.
 */
const LEGACY_GRAPH_OVERRIDES: Record<string, string | null> = {
  "apply-universal-credit": "dwp-universal-credit",
  "check-state-pension": "dwp-state-pension",
  "renew-driving-licence": null,
};

/**
 * Dirs superseded by a legacy sibling above — skipped to avoid emitting two
 * full services for the same thing.
 */
const SKIP_DIRS = new Set([
  "dwp-universal-credit", // superseded by apply-universal-credit
  "dwp-state-pension", // superseded by check-state-pension
  "dvla.renew-driving-licence", // superseded by renew-driving-licence
]);

function hasAllArtefacts(dir: string): boolean {
  return CORE_ARTEFACTS.every((f) =>
    fs.existsSync(path.join(SVC_DIR, dir, f)),
  );
}

function readJson(dir: string, file: string): Record<string, unknown> {
  return JSON.parse(fs.readFileSync(path.join(SVC_DIR, dir, file), "utf-8"));
}

function main(): void {
  const graphIds = new Set(
    new ServiceGraphEngine().getServices().map((n: { id: string }) => n.id),
  );

  const dirs = fs
    .readdirSync(SVC_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .filter(hasAllArtefacts)
    .filter((d) => !SKIP_DIRS.has(d))
    .sort();

  const generated: FullServiceData[] = dirs.map((dir) => {
    const manifest = readJson(dir, "manifest.json");
    let graphId: string | null;
    if (dir in LEGACY_GRAPH_OVERRIDES) {
      graphId = LEGACY_GRAPH_OVERRIDES[dir];
    } else if (graphIds.has(dir)) {
      graphId = dir;
    } else {
      graphId = null;
    }
    return {
      dirName: dir,
      graphId,
      manifest,
      policy: readJson(dir, "policy.json"),
      stateModel: readJson(dir, "state-model.json"),
      consent: readJson(dir, "consent.json"),
    };
  });

  // Preserve synthetic entries that have no directory on disk (e.g. agent-chat,
  // triage) so they are not lost when the file is regenerated.
  const generatedDirs = new Set(generated.map((e) => e.dirName));
  const synthetic = EXISTING.filter(
    (e) => !generatedDirs.has(e.dirName) && !hasAllArtefacts(e.dirName),
  );

  const all = [...generated, ...synthetic];

  const header = `/**
 * Embedded full-artefact service data.
 *
 * These are the ${all.length} services with complete manifest/policy/state-model/consent
 * artefacts from data/services/. They are embedded here so they can be seeded
 * on Cloudflare Workers where filesystem access is unavailable.
 *
 * GENERATED by scripts/generate-full-services.ts — do not edit by hand.
 * Run: npm run generate:full-services
 *
 * Each entry includes a graphId mapping — when the manifest ID differs from
 * the graph node ID, the graphId is used as the DB primary key so the full
 * entry replaces the graph-only entry during seeding.
 */

export interface FullServiceData {
  /** Directory name (e.g. "apply-universal-credit") */
  dirName: string;
  /** Graph node ID to replace, or null if no graph equivalent */
  graphId: string | null;
  manifest: Record<string, unknown>;
  policy: Record<string, unknown>;
  stateModel: Record<string, unknown>;
  consent: Record<string, unknown>;
}

export const FULL_SERVICES: FullServiceData[] = `;

  const body = JSON.stringify(all, null, 2);
  fs.writeFileSync(OUT, `${header}${body};\n`, "utf-8");

  console.log(`[generate-full-services] Wrote ${OUT}`);
  console.log(`  Generated from disk: ${generated.length}`);
  console.log(`  Synthetic preserved: ${synthetic.length} (${synthetic
    .map((e) => e.dirName)
    .join(", ")})`);
  console.log(`  Total embedded:      ${all.length}`);
}

main();
